Allow to sort dynamic fields
oxeanbits/graphoid pull request #7
Opened 2022-11-29 03:11 UTC by Victorcorcos

# Description ✍️

Allow to sort dynamic fields with this pattern:

* `order: { dynamicFields: { integer_test: ASC, string_test: DESC } }`

Example

```rb
{
    records(where: { sheetId: "62c46be8a6af030113ffb9bf" }, order: { dynamicFields: { integer_test: ASC, string_test: DESC } }) {
        count
        data {
            id
            dynamicFields
        }
    }
}
```

# Overview 🔍

# Checks ☑️

- [ ] Allow to sort dynamic fields

2022-11-29 20:30 UTC, niltonvasques requested changes
:diving_mask:

2022-11-29 20:30 UTC, niltonvasques commented on lib/graphoid/definitions/sorter.rb
> +            next argument(name, Sorter.dynamic_type) if name == 'dynamicFields'
What about instead have our field here hardcoded, we have some kind of metaprogramming informing that the field is dynamic? Find an idea

![image](https://user-images.githubusercontent.com/2291529/204641094-48ea1f9b-e97c-418f-b43c-8deca24a53a1.png)

2022-11-29 21:10 UTC, Victorcorcos commented on lib/graphoid/definitions/sorter.rb
> +            next argument(name, Sorter.dynamic_type) if name == 'dynamicFields'
Great idea! 🧠 

Let me see how to do it

2022-12-01 03:43 UTC, Victorcorcos commented
Done @niltonvasques

2022-12-01 14:00 UTC, niltonvasques requested changes
By doing this we can avoid the try dig on the other file

2022-12-01 14:00 UTC, niltonvasques commented on lib/graphoid/operators/attribute.rb
> +      @opts = opts
```suggestion
      @opts = opts
    end    
   
    def dynamic?
      @opts[:dynamic] == true
    end
```

2022-12-01 14:09 UTC, Victorcorcos commented on lib/graphoid/definitions/sorter.rb
> +            next argument(name, Sorter.dynamic_type) if field.try(:opts)&.dig(:dynamic)
```suggestion
            next argument(name, Sorter.dynamic_type) if field.dynamic?
```

2022-12-01 14:50 UTC, niltonvasques requested changes
Is working ? 

![image](https://user-images.githubusercontent.com/2291529/205083729-3007b182-2ee8-41c2-b9dd-4cbd12c49be4.png)


- [ ] missing tests

2022-12-01 15:25 UTC, Victorcorcos commented
> Is working ?

Yes, the Digitalize PR is pointing to this PR and the tests are passing (the last automated tests is executing this version).

2022-12-01 15:27 UTC, Victorcorcos commented on lib/graphoid/operators/attribute.rb
> +    end
```suggestion
```

2022-12-05 16:43 UTC, niltonvasques approved these changes

2022-12-05 16:44 UTC, merged